export { default as Navbar } from './Navbar/Navbar';
export { default as Button } from './Button/Button';
export { default as Card} from './Card/Card';
export { default as NavLinks} from './Navbar/NavLinks';
export { default as PersonalInformation } from './MultiForm/PersonalInformation';
export { default as VaccineDetails } from './MultiForm/VaccineDetails';
export { default as VaccineVerify } from './MultiForm/VaccineVerify';
export { default as NoRecord } from './MultiForm/NoRecord';
export { default as AddData } from './MultiForm/AddData';
export { default as RecordFound } from './MultiForm/RecordFound';
export { default as DownloadCertificate } from './MultiForm/DownloadCertificate';